In [15]:
import pandas as pd

In [10]:
df = pd.read_csv("/Users/naveen/Documents/Makeover_Mondays/listings.csv")

/anaconda3/envs/test1/lib/python3.4/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (43,61,62,94) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [11]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'summary',
       'space', 'description', 'experiences_offered', 'neighborhood_overview',
       ...
       'instant_bookable', 'is_business_travel_ready', 'cancellation_policy',
       'require_guest_profile_picture', 'require_guest_phone_verification',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object', length=106)

In [12]:
df.to_excel('/Users/naveen/Documents/Makeover_Mondays/MakeoverMonday_SydneyListings.xls',sheet_name='Data')

In [4]:
df.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,11156,https://www.airbnb.com/rooms/11156,20190511190711,2019-05-12,An Oasis in the City,Very central to the city which can be reached ...,Potts Pt. is a vibrant and popular inner-city...,Very central to the city which can be reached ...,none,"It is very close to everything and everywhere,...",...,f,f,moderate,f,f,1,0,1,0,1.61
1,12351,https://www.airbnb.com/rooms/12351,20190511190711,2019-05-12,Sydney City & Harbour at the door,Come stay with Vinh & Stuart (Awarded as one o...,"We're pretty relaxed hosts, and we fully appre...",Come stay with Vinh & Stuart (Awarded as one o...,none,"Pyrmont is an inner-city village of Sydney, on...",...,f,f,strict_14_with_grace_period,t,t,2,0,2,0,4.76
2,14250,https://www.airbnb.com/rooms/14250,20190511190711,2019-05-12,Manly Harbour House,"Beautifully renovated, spacious and quiet, our...",Our home is a thirty minute walk along the sea...,"Beautifully renovated, spacious and quiet, our...",none,Balgowlah Heights is one of the most prestigio...,...,f,f,strict_14_with_grace_period,f,f,2,2,0,0,0.05
3,15253,https://www.airbnb.com/rooms/15253,20190511190711,2019-05-12,Stunning Penthouse Apartment In Heart Of The City,Penthouse living in a great central location: ...,"A charming two-level, two-bedroom, two-bathroo...",Penthouse living in a great central location: ...,none,The location is really central and there is nu...,...,t,f,strict_14_with_grace_period,f,f,3,2,1,0,3.65
4,20865,https://www.airbnb.com/rooms/20865,20190511190711,2019-05-12,3 BED HOUSE + 1 BED STUDIO Balmain,Hi! We are a married professional couple with ...,HOUSE : _________ * DUCTED AIR CONDITIONING IN...,Hi! We are a married professional couple with ...,none,BALMAIN is an older inner city village / subur...,...,f,f,strict_14_with_grace_period,t,t,1,1,0,0,0.18

In [8]:
#checks for unique values in the column year. Should be done for all the above columns to check the 
#range of dimensions/measures in our data set
df.drop_duplicates('neighbourhood_group')

KeyError: 'neighbourhood_group'

In [14]:
df['price'].max()

'$999.00'

In [60]:
#to check the record count for each of the year dimensions

df.groupby(['Sex']).size().reset_index(name='Count')

     Sex  Count
0   Both    315
1    Men    315
2  Women    315

In [51]:
#To check the duplicate rows in the dataset

df_dups = df.duplicated(subset=None, keep='first')

In [54]:
#To check duplicates in the data set
df_dups.drop_duplicates()

0    False
dtype: bool

In [37]:
#checking for Null values
df[df.Year.notnull()]

,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both
5,2008,Annual,8.60,0.023,All days,15 years and over,Sleeping,Both
6,2009,Annual,8.67,0.023,All days,15 years and over,Sleeping,Both
7,2010,Annual,8.67,0.024,All days,15 years and over,Sleeping,Both
8,2011,Annual,8.71,0.026,All days,15 years and over,Sleeping,Both
9,2012,Annual,8.73,0.026,All days,15 years and over,Sleeping,Both
10,2013,Annual,8.74,0.027,All days,15 years and over,Sleeping,Both
11,2014,Annual,8.80,0.025,All days,15 years and over,Sleeping,Both
12,2015,Annual,8.83,0.027,All days,15 years and over,Sleeping,Both
13,2016,Annual,8.79,0.028,All days,15 years and over,Sleeping,Both
14,2017,Annual,8.80,0.027,All days,15 years and over,Sleeping,Both
15,2003,Annual,8.26,0.023,Nonholiday weekdays,15 years and over,Sleeping,Both
16,2004,Annual,8.25,0.034,Nonholiday weekdays,15 years and over,Sleeping,Both
17,2005,Annual,8.35,0.030,Nonholiday weekdays,15 years and over,Sleeping,Both
18,2006,Annual,8.33,0.032,Nonholiday weekdays,15 years and over,Sleeping,Both
19,2007,Annual,8.29,0.032,Nonholiday weekdays,15 years and over,Sleeping,Both
20,2008,Annual,8.30,0.032,Nonholiday weekdays,15 years and over,Sleeping,Both
21,2009,Annual,8.39,0.031,Nonholiday weekdays,15 years and over,Sleeping,Both
22,2010,Annual,8.38,0.031,Nonholiday weekdays,15 years and over,Sleeping,Both
23,2011,Annual,8.45,0.034,Nonholiday weekdays,15 years and over,Sleeping,Both
24,2012,Annual,8.45,0.034,Nonholiday weekdays,15 years and over,Sleeping,Both
25,2013,Annual,8.48,0.036,Nonholiday weekdays,15 years and over,Sleeping,Both
26,2014,Annual,8.54,0.031,Nonholiday weekdays,15 years and over,Sleeping,Both
27,2015,Annual,8.59,0.035,Nonholiday weekdays,15 years and over,Sleeping,Both
28,2016,Annual,8.50,0.037,Nonholiday weekdays,15 years and over,Sleeping,Both
29,2017,Annual,8.53,0.035,Nonholiday weekdays,15 years and over,Sleeping,Both
...,...,...,...,...,...,...,...,...
915,2003,Annual,9.18,0.072,Weekend days and holidays,65 years and over,Sleeping,Women
916,2004,Annual,9.05,0.067,Weekend days and holidays,65 years and over,Sleeping,Women
917,2005,Annual,9.28,0.119,Weekend days and holidays,65 years and over,Sleeping,Women
918,2006,Annual,8.94,0.094,Weekend days and holidays,65 years and over,Sleeping,Women
919,2007,Annual,9.13,0.104,Weekend days and holidays,65 years and over,Sleeping,Women
920,2008,Annual,9.31,0.099,Weekend days and holidays,65 years and over,Sleeping,Women
921,2009,Annual,9.21,0.083,Weekend days and holidays,65 years and over,Sleeping,Women
922,2010,Annual,9.22,0.094,Weekend days and holidays,65 years and over,Sleeping,Women
923,2011,Annual,9.29,0.094,Weekend days and holidays,65 years and over,Sleeping,Women
924,2012,Annual,9.06,0.104,Weekend days and holidays,65 years and over,Sleeping,Women
925,2013,Annual,9.06,0.091,Weekend days and holidays,65 years and over,Sleeping,Women
926,2014,Annual,9.13,0.094,Weekend days and holidays,65 years and over,Sleeping,Women
927,2015,Annual,9.30,0.086,Weekend days and holidays,65 years and over,Sleeping,Women
928,2016,Annual,9.10,0.081,Weekend days and holidays,65 years and over,Sleeping,Women
929,2017,Annual,9.15,0.100,Weekend days and holidays,65 years and over,Sleeping,Women
930,2003,Annual,8.70,0.060,Nonholiday weekdays,65 years and over,Sleeping,Women
931,2004,Annual,8.88,0.071,Nonholiday weekdays,65 years and over,Sleeping,Women
932,2005,Annual,8.81,0.081,Nonholiday weekdays,65 years and over,Sleeping,Women
933,2006,Annual,8.77,0.097,Nonholiday weekdays,65 years and over,Sleeping,Women
934,2007,Annual,8.82,0.088,Nonholiday weekdays,65 years and over,Sleeping,Women
935,2008,Annual,8.79,0.086,Nonholiday weekdays,65 years and over,Sleeping,Women
936,2009,Annual,8.86,0.083,Nonholiday weekdays,65 years and over,Sleeping,Women
937,2010,Annual,8.96,0.092,Nonholiday weekdays,65 years and over,Sleeping,Women
938,2011,Annual,9.02,0.085,Nonholiday weekdays,65 years and over,Sleeping,Women
939,2012,Annual,8.79,0.089,Nonholiday weekdays,65 years and over,Sleeping,Women
940,2013,Annual,8.83,0.085,Nonholiday weekdays,65 years and over,Sleeping,Women
941,2014,Annual,8.98,0.086,Nonholiday weekdays,65 years and over,Sleeping,Women
942,2015,Annual,8.83,0.074,Nonholiday weekdays,65 years and over,Sleeping,Women
943,2016,Annual,8.92,0.071,Nonholiday weekdays,65 years and over,Sleeping,Women
944,2017,Annual,8.81,0.091,Nonholiday weekdays,65 years and over,Sleeping,Women

In [33]:
df1.head()

,0,1,2,3,4,5,6,7,8,9,...,935,936,937,938,939,940,941,942,943,944
Year,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
Period,Annual,Annual,Annual,Annual,Annual,Annual,Annual,Annual,Annual,Annual,...,Annual,Annual,Annual,Annual,Annual,Annual,Annual,Annual,Annual,Annual
Avg hrs per day sleeping,8.57,8.55,8.62,8.63,8.57,8.6,8.67,8.67,8.71,8.73,...,8.79,8.86,8.96,9.02,8.79,8.83,8.98,8.83,8.92,8.81
Standard Error,0.018,0.026,0.023,0.024,0.024,0.023,0.023,0.024,0.026,0.026,...,0.086,0.083,0.092,0.085,0.089,0.085,0.086,0.074,0.071,0.091
Type of Days,All days,All days,All days,All days,All days,All days,All days,All days,All days,All days,...,Nonholiday weekdays,Nonholiday weekdays,Nonholiday weekdays,Nonholiday weekdays,Nonholiday weekdays,Nonholiday weekdays,Nonholiday weekdays,Nonholiday weekdays,Nonholiday weekdays,Nonholiday weekdays

In [23]:
#df2=df1.rename(columns=df1.iloc[0]).drop(df1.index[0])

In [24]:
#df2.to_excel('/Users/naveen/Documents/Makeover_Mondays/MakeoverMonday_3105.xls',sheet_name='Data')